app:
  build: .
  ports:
    - "5000-6000:5000-6000"
    - "80:80"
  restart: always
  environment:
  - SERVER_PORT=80
  - ALLOW_PERMANENT_RULES=false
  - EXPOSED_PORT_START_RANGE=5000
  - EXPOSED_PORT_END_RANGE=6000
  links:
    - "dummy_server"

dummy_server:
  image: jasonrm/dummy-server
  ports:
    - "80"