app:
  build: .
  ports:
    - "5000-6000:5000-6000"
  restart: always
  environment:
  - SERVER_PORT=80
  - ALLOW_PERMANENT_RULES=false
  - EXPOSED_PORT_START_RANGE=5000
  - EXPOSED_PORT_END_RANGE=6000
  cap_add:
  - NET_ADMIN
  - NET_RAW